---
title: "R challenge: University subject analysis"
author:
   - name: Andrew Moles
     affiliation: Learning Developer, Digital Skills Lab
date: today
#format:
#  html:
#    toc: true
#    toc-depth: 4
#    toc-location: left
    #toc-expand: false
#    code-fold: false
#    keep-md: false
#    embed-resources: true
#    number-sections: true
#    smooth-scroll: true
#    mainfont: roboto
#theme: 
#  - flatly
#  - css/roboto.css
#title-block-banner: "#15BC9B"
#title-block-banner-color: "#000508"
#css: css/styles.css
---

# Knowledge check

Test your R skills developed from completing the first two worksheets. You are tasked with seeing how LSE compares to other universities in the number of students taking different subjects. 

Can you solve this coding challenge without support from a trainer, peers, or AI? Solely relying on the R techniques you have learned so far, and your web searching skills?

Completing this project is the perfect way to test your learning!

# The challenge

Your task is to write R code that provides you with a table comparing the average number of students by subject area and university (LSE versus other universities). 

You will need to: 

- Make a new column that has the following categories - `LSE` and `Other universities`
- Calculate the average number of students by subject area and by the above category you made

When you run your code it should load in your dataset, apply the above data preparation, and give you a table of the results. From your results you should be able to answer the following questions:

- Which subject area at LSE has the highest average number of students?   
- Which subject area at the other universities has the highest average number of students?

The data can be loaded into R using the following URL: `https://raw.githubusercontent.com/andrewmoles2/HE-students/refs/heads/main/data/he_subjects_20_24.csv`. 

The data is from the [HESA website](https://www.hesa.ac.uk/data-and-analysis/students){target='_blank'}, which has been prepared for you. The dataset shows what subject areas students are doing at different universities. It covers academic years from 2014/2015 to 2023/2024.

We recommend you open a new R Markdown or R Script for this challenge by going to `File -> New File ->` and selecting Markdown or R Script. Be sure to save your work in the same folder as the rest of your code when you are done. 


```{r solution}
#| eval: false
#| message: false
#| warning: false
#| include: false

library(tidyverse)
library(janitor)

he_subjects <- read_csv('https://raw.githubusercontent.com/andrewmoles2/HE-students/refs/heads/main/data/he_subjects_20_24.csv') %>%
  clean_names()

per_subject_agg <- he_subjects %>%
  mutate(lse = ifelse(he_provider == "London School of Economics and Political Science", "LSE", "Other universities")) %>%
  group_by(subject_areas, lse) %>%
  summarise(avg_students_per_year = mean(n_students, na.rm = TRUE)) %>%
  arrange(desc(avg_students_per_year))

per_subject_agg

# validation to check how it calculated averages
lse <- he_subjects %>%
  filter(he_provider == "London School of Economics and Political Science")
```

# How do I know if got it right?

Answer some questions in [this quiz](https://forms.office.com/e/W0t7pRQX9i){target='_blank'} to test out if you got the expected outcome. 

As a bonus, you will get our solution at the end of the quiz. 

